GET http://localhost:1234/familia

###
GET http://localhost:1234/
### Para crear una cosa
POST http://localhost:1234/pokemon
Content-Type: application/json

{
  "nombre": "Gonzalez",
  "integrantes": 4,
  "pais": "Argentina"
}



## Api Rest con Node.js y Express
### Recuperar una Pelicula por su ID
GET http://localhost:1234/movies/

### Recuperar todas las Peliculas por un genero
GET http://localhost:1234/movies?genre=HORROR

### Crear una nueva pelicula
POST http://localhost:1234/movies/
Content-Type: application/json

{
    "title": "Digital Dream",
    "year": 1971,
    "genre": "Horror",
    "director": "Steven Spielberg",
    "rating": 8.8,
    "duration": 142,
    "description": "An exciting drama movie that captivates audiences.",
    "image": "https://example.com/digital_dream.jpg"
}


### Actualizar una pelicula
PATCH http://localhost:1234/movies/6
Content-Type: application/json

{
  "year": 2006
}