GET http://localhost:1234/familia

###
GET http://localhost:1234/
### Para crear una cosa
POST http://localhost:1234/pokemon
Content-Type: application/json

{
  "nombre": "Gonzalez",
  "integrantes": 4,
  "pais": "Argentina"
}



## Api Rest con Node.js y Express
### Recuperar una Pelicula por su ID
GET http://localhost:1234/movies/1 

### Recuperar todas las Peliculas por un genero
GET http://localhost:1234/movies?genre=ACTION